
library fabrcore {
 inputs:
  driver/Constants.h
  driver/Driver.cpp
  driver/Driver.h
  driver/ExitCode.h
  driver/Options.cpp
  driver/Options.h
  exec/BuildExecutor.h
  exec/ProcessResult.h
  exec/UnixExec.cpp
  model/BuildModel.cpp
  model/BuildModel.h
  model/BuildRule.cpp
  model/BuildRule.h
  model/BuildTarget.cpp
  model/BuildTarget.h
  parser/BuildFile.h
  support/DependencyQueue.h
  support/Path.h
  support/Symbol.cpp
  support/Symbol.h
}

program fabr {
  driver/main.cpp
  fabrcore
}

