name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: ./bootstrap.sh
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: ./bootstrap.sh
